version: '3'
services:
  sql_db:
    image: 'postgres:13.1-alpine'
    container_name: sql_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "54328:5432"
    volumes:
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - currency-network
   
  currency-exchange:
    container_name: currency-exchange-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
       - "8001:8001"
    depends_on:
      - sql_db
    networks:
      - currency-network
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sql_db:5432/postgres
      - SPRING_DATASOURCE_PASSWORD=root

networks:
  currency-network:
    driver: bridge
